name = "houzs-erp-sales"
compatibility_date = "2026-04-22"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "houzs-erp"
database_id = "1ad7ccf2-d84b-4438-8641-7b43c2b2bc87"
