-- 017_case_tracking.sql
-- Replace the account-based Customer Portal with tokenised per-case
-- tracking. Customers enter their ASSR number + phone on a public
-- /track page, server issues a short-lived token scoped to that one
-- case. Dispatcher can also generate a staff-sourced (longer-lived)
-- token and share the link via WhatsApp.

-- ── Per-case track tokens ────────────────────────────────────
CREATE TABLE IF NOT EXISTS case_track_tokens (
  token TEXT PRIMARY KEY,
  assr_id INTEGER NOT NULL,
  -- 'customer' tokens come from the /track form, short TTL (30 min).
  -- 'staff' tokens are generated by a dispatcher for sharing, 30-day TTL.
  source TEXT NOT NULL DEFAULT 'customer'
    CHECK(source IN ('customer','staff')),
  -- Stored so we can attribute the anonymous session's activity back
  -- to the phone that authenticated it. NULL for staff-generated tokens.
  verified_phone TEXT,
  expires_at TEXT NOT NULL,
  created_at TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (assr_id) REFERENCES assr_cases(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_case_track_assr ON case_track_tokens(assr_id);
CREATE INDEX IF NOT EXISTS idx_case_track_exp ON case_track_tokens(expires_at);

-- ── Drop the account-based portal tables ────────────────────
-- No real usage yet — we're swapping before anyone onboards.
DROP TABLE IF EXISTS customer_sessions;
DROP TABLE IF EXISTS customer_invitations;
DROP TABLE IF EXISTS customer_accounts;

-- NOTE: `assr_cases.customer_id`, `assr_activity.customer_id`, and
-- `assr_attachments.customer_id` columns are left in place — SQLite
-- doesn't support DROP COLUMN without rebuilding the table. They're
-- harmless (nullable integers, no FK constraint now that the target
-- table is gone) and will simply remain NULL from here on. The
-- `source` and `visible_to_customer` columns continue to be used.
