-- 104_restore_is_active_defaults.sql  (D1 / SQLite test mirror — intentional NO-OP)
--
-- The real change — restore `DEFAULT 1` on several is_active columns — is a
-- Postgres-prod concern and now lives in
--   migrations-pg/0054_restore_is_active_defaults.sql
--
-- It was originally written here as raw `ALTER TABLE … ALTER COLUMN … SET DEFAULT`,
-- which is Postgres-only syntax. SQLite/D1 has no `ALTER COLUMN`, so this file
-- crashed the D1 test-migration runner (tests/setup.ts) and with it the backend
-- CI / deploy gate.
--
-- In the ephemeral D1 test database every table is recreated fresh from its
-- CREATE TABLE in an earlier migration, so there is no column default to
-- "restore" here. This file is intentionally a no-op, kept only so the D1
-- numbered-migration sequence stays aligned with migrations-pg.
SELECT 1;
