-- Seed users table from src/lib/sales-store.ts seedMembers.
-- INSERT OR IGNORE so re-running the migration is safe.
-- No BEGIN/COMMIT — D1 wraps the whole file in a single transaction.

-- ── Bootstrap admin (logs in out-of-the-box) ────────────────────────
INSERT OR IGNORE INTO users (id, name, code, email, phone, position, join_date, status, assigned_brands, commission_tiers, min_rate, password_hash, password_salt, must_change_password) VALUES (
  'dir-hello', 'HOUZS ADMIN', 'ADMIN', 'hello@houzscentury.com', NULL, 'Sales Director', '2024-01-01', 'ACTIVE', '["AKEMI","ZANOTTI","ERGOTEX","DUNLOPILLO","HOUZS"]', '[]', 0, 'ictSyckPxNuHo6zyGCd1AQKBYRQLoF+y3M0L4M5oUkg=', 'eYQoDIrLc7bGF2d718LIGQ==', 0
);

INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('dir-kingsley', 'KINGSLEY', 'KINGSLEY', 'shopckingsley@gmail.com', '+60123570401', NULL, 'Sales Director', NULL, '[]', '2024-01-01', 'ACTIVE', '["AKEMI", "ZANOTTI"]', '[{"threshold": 0, "pct": 14}]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('dir-peter', 'PETER', 'PETER', 'yzhe212@gmail.com', '+601128858819', NULL, 'Sales Director', 'dir-kingsley', '[]', '2024-01-01', 'ACTIVE', '["AKEMI"]', '[{"threshold": 0, "pct": 12}]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('dir-kris', 'KRIS', 'KRIS', 'suihor00@gmail.com', '+60126008198', NULL, 'Sales Director', 'dir-kingsley', '[]', '2024-01-01', 'ACTIVE', '[]', '[{"threshold": 0, "pct": 12}]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-shawn', 'SHAWN', 'SHAWN', 'gajeel333@gmail.com', '+60109820330', NULL, 'Sales Executive', 'dir-peter', '[]', '2024-01-15', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-stanley', 'STANLEY', 'STANLEY', 'shopcstanley@gmail.com', '+601127139334', NULL, 'Sales Executive', 'dir-kingsley', '[]', '2024-01-15', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-anthony', 'ANTHONY', 'ANTHONY', 'hongchang6666@gmail.com', '+60164078555', NULL, 'Sales Executive', 'dir-peter', '[]', '2024-02-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-lawrence', 'LAWRENCE', 'LAWRENCE', 'Jiankhuan01@gmail.com', '+60164600347', NULL, 'Sales Executive', 'dir-peter', '[]', '2024-02-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-junie', 'JUNIE', 'JUNIE', 'junie.nini910@gmail.com', '+60174701988', NULL, 'Sales Executive', 'dir-peter', '[]', '2024-02-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-meiting', 'MEI TING', 'MEI TING', 'ymting3943@gmail.com', '+60163375592', NULL, 'Sales Executive', 'dir-peter', '[]', '2024-03-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-cheahuan', 'CHEA HUAN', 'CHEA HUAN', 'cheahuan520@gmail.com', '+60164207508', NULL, 'Sales Executive', 'dir-kingsley', '[]', '2024-03-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-yang', 'YANG', 'YANG', 'somenoe98@gmail.com', '+60162143943', NULL, 'Sales Executive', 'dir-kingsley', '[]', '2024-03-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-yuny', 'YUNY', 'YUNY', 'ziyunc90@gmail.com', '+60165590827', NULL, 'Sales Executive', 'exe-anthony', '[]', '2024-04-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-rachael', 'RACHAEL', 'RACHAEL', 'Rachael.Lim01@gmail.com', '+601111225524', NULL, 'Sales Executive', 'dir-kingsley', '[]', '2024-04-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-weihow', 'WEI HOW', 'WEI HOW', 'ganweihow0703@gmail.com', '+60175269363', NULL, 'Sales Executive', 'dir-kingsley', '[]', '2024-04-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-weipin', 'WEIPIN NGIAU', 'WEIPIN', 'ngiauweipin01@gmail.com', '+60177371838', NULL, 'Sales Executive', 'exe-shawn', '[]', '2024-05-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-peifen', 'PEIFEN', 'Peifen', 'peifenv1228@gmail.com', '+60164748893', NULL, 'Sales Executive', 'exe-shawn', '[]', '2024-05-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-sally', 'SALLY', 'SALLY', 'k.c.thing.kct@gmail.com', '+60139821886', NULL, 'Sales Executive', 'exe-shawn', '[]', '2024-06-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-jane', 'JANE', 'JANE', 'ooij121@gmail.com', '+601111411606', NULL, 'Sales Executive', 'exe-shawn', '[]', '2024-06-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-chongyee', 'CHONG CHAN YEE', 'MELVIN CHONG', 'Ahzhang0408@gmail.com', '+60122895355', NULL, 'Sales Executive', 'exe-stanley', '[]', '2024-05-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-soojia', 'SOO JIA XIAN', 'ETHAN SOO', 'xianxian0610@gmail.com', '+60165210308', NULL, 'Sales Executive', 'exe-stanley', '[]', '2024-05-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-sheldon', 'SHELDON TAN', 'SHELDON', 'donghongtan@gmail.com', '+60108274584', NULL, 'Sales Executive', 'exe-stanley', '[]', '2024-05-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-james', 'JAMES SEOW AIK HOOI', 'JAMES SEOW', 'aikhooi456@gmail.com', '+60168423662', NULL, 'Sales Executive', 'exe-stanley', '[]', '2024-05-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-lucas', 'TAN JIA HOU', 'LUCAS', 'shopc.jhou@gmail.com', '+60164863706', NULL, 'Sales Executive', 'exe-stanley', '[]', '2024-06-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-esther', 'ESTHER CHONG', 'ESTHER CHONG', 'estherchong8188@gmail.com', '+60194720066', NULL, 'Sales Executive', 'exe-stanley', '[]', '2024-06-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-adrian', 'ADRIAN', 'ADRIAN', 'adrianleejialiang000125@gmail.com', '+601161406162', NULL, 'Sales Executive', 'exe-stanley', '[]', '2024-07-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-karjiun', 'TAN KAR JIUN', 'TAN KAR JIUN', 'shopckarjiun@gmail.com', '+601120420427', NULL, 'Sales Executive', 'exe-stanley', '[]', '2024-07-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-stephy', 'STEPHY', 'STEPHY', 'jxuan060298@gmail.com', '+60174113223', NULL, 'Sales Executive', 'exe-anthony', '[]', '2024-06-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-jonas', 'SIA JONAS', 'SIA JONAS', 'jonassia040212@gmail.com', '+60195714625', NULL, 'Sales Executive', 'exe-anthony', '[]', '2024-07-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-luis', 'LUIS', 'LUIS', 'teochinghuan@gmail.com', '+601110938255', NULL, 'Sales Executive', 'exe-lawrence', '[]', '2024-07-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-phoebe', 'YEAP MIN HUA', 'Phoebe', 'minhua1607@gmail.com', '+60165236652', NULL, 'Sales Executive', 'exe-junie', '[]', '2024-08-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-yauwei', 'LIM YAU WEI', 'Lim Yau Wei', 'limyauwei7602@gmail.com', '+60124007602', NULL, 'Sales Executive', 'exe-cheahuan', '[]', '2024-06-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-zack', 'ONG ZI MIN', 'Zack', 'ongzimin@gmail.com', '+60165109198', NULL, 'Sales Executive', 'exe-cheahuan', '[]', '2024-08-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-shiting', 'CHANG SHI TING', 'CHANG SHI TING', 'cshiting35@gmail.com', '+60169508618', NULL, 'Sales Executive', 'exe-yang', '[]', '2024-08-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-wenggi', 'WENGGI', 'WENGGI', 'foowenggi@gmail.com', '+60125131162', NULL, 'Sales Executive', 'exe-yuny', '[]', '2024-05-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-hwasheng', 'TEH HWA SHENG', 'Hwasheng', 'tehhwasheng25052001@gmail.com', '+601127441525', NULL, 'Sales Executive', 'dir-peter', '[]', '2024-04-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-xiaorou', 'LEE SZE ROU', 'XIAO ROU', 'bbxiaorou.0709@gmail.com', '+601110887296', NULL, 'Sales Executive', 'dir-kingsley', '[]', '2024-06-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-others', 'OTHERS', 'OTHERS', NULL, NULL, NULL, 'Sales Executive', NULL, '[]', '2024-01-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-siang', 'SIANG', 'SIANG', NULL, NULL, NULL, 'Sales Executive', NULL, '[]', '2024-01-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-alvin', 'ALVIN', 'ALVIN', NULL, NULL, NULL, 'Sales Executive', NULL, '[]', '2024-01-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-alex', 'ALEX', 'ALEX', NULL, NULL, NULL, 'Sales Executive', NULL, '[]', '2024-01-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-ww', 'WW', 'WW', NULL, NULL, NULL, 'Sales Executive', NULL, '[]', '2024-01-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-mk', 'MK', 'MK', NULL, NULL, NULL, 'Sales Executive', NULL, '[]', '2024-01-01', 'ACTIVE', '[]', '[]', 0);
INSERT OR IGNORE INTO users (id, name, code, email, phone, ic, position, parent_id, additional_parent_ids, join_date, status, assigned_brands, commission_tiers, min_rate) VALUES ('exe-liang', 'LIANG', 'LIANG', NULL, NULL, NULL, 'Sales Executive', NULL, '[]', '2024-01-01', 'ACTIVE', '[]', '[]', 0);