-- Default role_permissions matrix (admin can override any cell via UI).
-- Uses INSERT OR IGNORE so re-running the migration is safe.

INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Super Admin', 'dashboard', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Super Admin', 'calendar', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Super Admin', 'finance', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Super Admin', 'pms', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Super Admin', 'settings', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Super Admin', 'sales_team', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Super Admin', 'so_details', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Super Admin', 'so', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Super Admin', 'sku_costing', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Super Admin', 'qms', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Super Admin', 'bd', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Super Admin', 'operation', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Super Admin', 'driver', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Super Admin', 'admin_users', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Super Admin', 'admin_audit', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Super Admin', 'admin_permissions', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'HR Manager', 'dashboard', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'HR Manager', 'calendar', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'HR Manager', 'finance', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'HR Manager', 'pms', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'HR Manager', 'settings', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'HR Manager', 'sales_team', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'HR Manager', 'so_details', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'HR Manager', 'so', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'HR Manager', 'sku_costing', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'HR Manager', 'qms', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'HR Manager', 'bd', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'HR Manager', 'operation', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'HR Manager', 'driver', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'HR Manager', 'admin_users', 'EDIT');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'HR Manager', 'admin_audit', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'HR Manager', 'admin_permissions', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Finance Manager', 'dashboard', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Finance Manager', 'calendar', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Finance Manager', 'finance', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Finance Manager', 'pms', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Finance Manager', 'settings', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Finance Manager', 'sales_team', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Finance Manager', 'so_details', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Finance Manager', 'so', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Finance Manager', 'sku_costing', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Finance Manager', 'qms', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Finance Manager', 'bd', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Finance Manager', 'operation', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Finance Manager', 'driver', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Finance Manager', 'admin_users', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Finance Manager', 'admin_audit', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Finance Manager', 'admin_permissions', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Admin Assistant', 'dashboard', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Admin Assistant', 'calendar', 'EDIT');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Admin Assistant', 'finance', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Admin Assistant', 'pms', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Admin Assistant', 'settings', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Admin Assistant', 'sales_team', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Admin Assistant', 'so_details', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Admin Assistant', 'so', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Admin Assistant', 'sku_costing', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Admin Assistant', 'qms', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Admin Assistant', 'bd', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Admin Assistant', 'operation', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Admin Assistant', 'driver', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Admin Assistant', 'admin_users', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Admin Assistant', 'admin_audit', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('HQ', 'Admin Assistant', 'admin_permissions', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Director', 'dashboard', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Director', 'calendar', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Director', 'finance', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Director', 'pms', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Director', 'settings', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Director', 'sales_team', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Director', 'so_details', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Director', 'so', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Director', 'sku_costing', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Director', 'qms', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Director', 'bd', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Director', 'operation', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Director', 'driver', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Director', 'admin_users', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Director', 'admin_audit', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Director', 'admin_permissions', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Manager', 'dashboard', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Manager', 'calendar', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Manager', 'finance', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Manager', 'pms', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Manager', 'settings', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Manager', 'sales_team', 'EDIT');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Manager', 'so_details', 'EDIT');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Manager', 'so', 'EDIT');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Manager', 'sku_costing', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Manager', 'qms', 'EDIT');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Manager', 'bd', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Manager', 'operation', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Manager', 'driver', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Manager', 'admin_users', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Manager', 'admin_audit', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Manager', 'admin_permissions', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Executive', 'dashboard', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Executive', 'calendar', 'EDIT');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Executive', 'finance', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Executive', 'pms', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Executive', 'settings', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Executive', 'sales_team', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Executive', 'so_details', 'EDIT');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Executive', 'so', 'EDIT');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Executive', 'sku_costing', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Executive', 'qms', 'EDIT');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Executive', 'bd', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Executive', 'operation', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Executive', 'driver', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Executive', 'admin_users', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Executive', 'admin_audit', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Executive', 'admin_permissions', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Trainee', 'dashboard', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Trainee', 'calendar', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Trainee', 'finance', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Trainee', 'pms', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Trainee', 'settings', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Trainee', 'sales_team', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Trainee', 'so_details', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Trainee', 'so', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Trainee', 'sku_costing', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Trainee', 'qms', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Trainee', 'bd', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Trainee', 'operation', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Trainee', 'driver', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Trainee', 'admin_users', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Trainee', 'admin_audit', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('SALES', 'Sales Trainee', 'admin_permissions', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Director', 'dashboard', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Director', 'calendar', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Director', 'finance', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Director', 'pms', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Director', 'settings', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Director', 'sales_team', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Director', 'so_details', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Director', 'so', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Director', 'sku_costing', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Director', 'qms', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Director', 'bd', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Director', 'operation', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Director', 'driver', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Director', 'admin_users', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Director', 'admin_audit', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Director', 'admin_permissions', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Manager', 'dashboard', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Manager', 'calendar', 'EDIT');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Manager', 'finance', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Manager', 'pms', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Manager', 'settings', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Manager', 'sales_team', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Manager', 'so_details', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Manager', 'so', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Manager', 'sku_costing', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Manager', 'qms', 'EDIT');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Manager', 'bd', 'EDIT');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Manager', 'operation', 'FULL');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Manager', 'driver', 'EDIT');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Manager', 'admin_users', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Manager', 'admin_audit', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Manager', 'admin_permissions', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Executive', 'dashboard', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Executive', 'calendar', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Executive', 'finance', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Executive', 'pms', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Executive', 'settings', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Executive', 'sales_team', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Executive', 'so_details', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Executive', 'so', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Executive', 'sku_costing', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Executive', 'qms', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Executive', 'bd', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Executive', 'operation', 'EDIT');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Executive', 'driver', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Executive', 'admin_users', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Executive', 'admin_audit', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Ops Executive', 'admin_permissions', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Warehouse', 'dashboard', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Warehouse', 'calendar', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Warehouse', 'finance', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Warehouse', 'pms', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Warehouse', 'settings', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Warehouse', 'sales_team', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Warehouse', 'so_details', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Warehouse', 'so', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Warehouse', 'sku_costing', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Warehouse', 'qms', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Warehouse', 'bd', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Warehouse', 'operation', 'EDIT');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Warehouse', 'driver', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Warehouse', 'admin_users', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Warehouse', 'admin_audit', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Warehouse', 'admin_permissions', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Driver', 'dashboard', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Driver', 'calendar', 'VIEW');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Driver', 'finance', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Driver', 'pms', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Driver', 'settings', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Driver', 'sales_team', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Driver', 'so_details', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Driver', 'so', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Driver', 'sku_costing', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Driver', 'qms', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Driver', 'bd', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Driver', 'operation', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Driver', 'driver', 'EDIT');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Driver', 'admin_users', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Driver', 'admin_audit', 'NONE');
INSERT OR IGNORE INTO role_permissions (department, position, module_key, level) VALUES ('OPERATION', 'Driver', 'admin_permissions', 'NONE');