-- 0002_indexes.sql — all B-tree indexes carried over from the D1 schema.
-- Generated from the D1 export (scripts/gen-index-migration.mjs). Every
-- statement is IF NOT EXISTS so this is safe to re-run / apply to a DB that
-- already has the indexes. Keep this in the tracked migration history so a
-- fresh load (loader builds tables, pg-migrate applies this) is fully indexed
-- and never silently sequential-scans. 194 indexes.

CREATE INDEX IF NOT EXISTS idx_assr_activity_archived    ON assr_activity(archived_at);
CREATE INDEX IF NOT EXISTS idx_assr_activity_case ON assr_activity(assr_id);
CREATE INDEX IF NOT EXISTS idx_assr_activity_category ON assr_activity(assr_id, category);
CREATE INDEX IF NOT EXISTS idx_assr_activity_refs ON assr_activity(references_entry_id);
CREATE INDEX IF NOT EXISTS idx_assr_activity_source ON assr_activity(source_channel);
CREATE INDEX IF NOT EXISTS idx_assr_alert_acks_active ON assr_alert_acks(assr_id, stage, event, snoozed_until);
CREATE INDEX IF NOT EXISTS idx_assr_alert_acks_case  ON assr_alert_acks(assr_id);
CREATE INDEX IF NOT EXISTS idx_assr_approved_by     ON assr_cases(approved_by);
CREATE INDEX IF NOT EXISTS idx_assr_assigned        ON assr_cases(assigned_to);
CREATE INDEX IF NOT EXISTS idx_assr_attachments_archived ON assr_attachments(archived_at);
CREATE INDEX IF NOT EXISTS idx_assr_attachments_case ON assr_attachments(assr_id);
CREATE INDEX IF NOT EXISTS idx_assr_cases_archived  ON assr_cases(archived_at);
CREATE INDEX IF NOT EXISTS idx_assr_cases_customer  ON assr_cases(customer_id);
CREATE INDEX IF NOT EXISTS idx_assr_cases_verification_outcome ON assr_cases(verification_outcome) WHERE verification_outcome IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_assr_creditor_code   ON assr_cases(creditor_code);
CREATE INDEX IF NOT EXISTS idx_assr_customer_email  ON assr_cases(customer_email);
CREATE INDEX IF NOT EXISTS idx_assr_deadline        ON assr_cases(deadline_at);
CREATE INDEX IF NOT EXISTS idx_assr_issue_cat_active ON assr_issue_categories(active);
CREATE INDEX IF NOT EXISTS idx_assr_items_case ON assr_items(assr_id);
CREATE INDEX IF NOT EXISTS idx_assr_items_ready     ON assr_cases(items_ready_at);
CREATE INDEX IF NOT EXISTS idx_assr_lead_time_prof  ON assr_cases(lead_time_profile_id);
CREATE INDEX IF NOT EXISTS idx_assr_logistics_archived   ON assr_logistics(archived_at);
CREATE INDEX IF NOT EXISTS idx_assr_logistics_case ON assr_logistics(assr_id);
CREATE INDEX IF NOT EXISTS idx_assr_lt_acts_at      ON assr_lead_time_activations(activated_at);
CREATE INDEX IF NOT EXISTS idx_assr_lt_acts_profile ON assr_lead_time_activations(profile_id, activated_at);
CREATE INDEX IF NOT EXISTS idx_assr_lt_amend_profile ON assr_lead_time_amendments(profile_id, created_at);
CREATE INDEX IF NOT EXISTS idx_assr_lt_sched_pending ON assr_lead_time_scheduled_activations(status, scheduled_for);
CREATE INDEX IF NOT EXISTS idx_assr_ncr             ON assr_cases(ncr_category);
CREATE INDEX IF NOT EXISTS idx_assr_ncr_active ON assr_ncr_categories(active);
CREATE INDEX IF NOT EXISTS idx_assr_priorities_active ON assr_priorities(active);
CREATE INDEX IF NOT EXISTS idx_assr_priority_stage_targets_lookup ON assr_priority_stage_targets(priority_id, stage);
CREATE INDEX IF NOT EXISTS idx_assr_resolution_active ON assr_resolution_methods(active);
CREATE INDEX IF NOT EXISTS idx_assr_stage           ON assr_cases(stage);
CREATE INDEX IF NOT EXISTS idx_assr_stage_changed   ON assr_cases(stage_changed_at);
CREATE INDEX IF NOT EXISTS idx_assr_stage_entered   ON assr_cases(stage_entered_at);
CREATE INDEX IF NOT EXISTS idx_assr_stage_history_case  ON assr_stage_history(assr_id);
CREATE INDEX IF NOT EXISTS idx_assr_stage_history_open  ON assr_stage_history(assr_id, exited_at);
CREATE INDEX IF NOT EXISTS idx_assr_stage_targets_profile ON assr_stage_targets(profile_id);
CREATE INDEX IF NOT EXISTS idx_assr_status          ON assr_cases(status);
CREATE INDEX IF NOT EXISTS idx_assr_supplier_pickup ON assr_cases(supplier_pickup_at);
CREATE INDEX IF NOT EXISTS idx_assr_supplier_tokens_case  ON assr_supplier_tokens(assr_id);
CREATE INDEX IF NOT EXISTS idx_assr_supplier_tokens_token ON assr_supplier_tokens(token);
CREATE INDEX IF NOT EXISTS idx_awards_active_sort ON awards(active, sort_order, id);
CREATE INDEX IF NOT EXISTS idx_case_track_assr ON case_track_tokens(assr_id);
CREATE INDEX IF NOT EXISTS idx_case_track_exp ON case_track_tokens(expires_at);
CREATE INDEX IF NOT EXISTS idx_clock_date ON driver_clock_records(clock_date);
CREATE INDEX IF NOT EXISTS idx_clock_user ON driver_clock_records(user_id);
CREATE INDEX IF NOT EXISTS idx_compliance_expiry ON lorry_compliance(expiry_date);
CREATE INDEX IF NOT EXISTS idx_compliance_lorry ON lorry_compliance(lorry_id);
CREATE INDEX IF NOT EXISTS idx_creditors_company_name ON creditors(company_name);
CREATE INDEX IF NOT EXISTS idx_creditors_currency ON creditors(currency_code);
CREATE INDEX IF NOT EXISTS idx_creditors_type ON creditors(type);
CREATE INDEX IF NOT EXISTS idx_dsl_doc ON delivery_status_log(doc_no);
CREATE INDEX IF NOT EXISTS idx_dt_est_delivery ON delivery_tracking(est_delivery_date);
CREATE INDEX IF NOT EXISTS idx_dt_region ON delivery_tracking(region);
CREATE INDEX IF NOT EXISTS idx_dt_shipout ON delivery_tracking(shipout_date);
CREATE INDEX IF NOT EXISTS idx_dt_status ON delivery_tracking(status);
CREATE INDEX IF NOT EXISTS idx_dt_trip ON delivery_tracking(trip_id);
CREATE INDEX IF NOT EXISTS idx_email_log_purpose ON email_log(purpose, created_at);
CREATE INDEX IF NOT EXISTS idx_email_log_ref ON email_log(ref_type, ref_id);
CREATE INDEX IF NOT EXISTS idx_events_date ON events(event_date);
CREATE INDEX IF NOT EXISTS idx_events_type ON events(type);
CREATE INDEX IF NOT EXISTS idx_idea_att_target ON idea_attachments(target_type, target_id, archived_at);
CREATE INDEX IF NOT EXISTS idx_idea_comments_target ON idea_comments(target_type, target_id, archived_at);
CREATE INDEX IF NOT EXISTS idx_idea_comments_user ON idea_comments(user_id);
CREATE INDEX IF NOT EXISTS idx_incident_date ON lorry_incidents(incident_date);
CREATE INDEX IF NOT EXISTS idx_incident_lorry ON lorry_incidents(lorry_id);
CREATE INDEX IF NOT EXISTS idx_innovations_archived ON innovations(archived_at);
CREATE INDEX IF NOT EXISTS idx_innovations_status_created ON innovations(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_innovations_user_created   ON innovations(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inspection_date ON daily_inspections(inspection_date);
CREATE INDEX IF NOT EXISTS idx_inspection_lorry ON daily_inspections(lorry_id);
CREATE INDEX IF NOT EXISTS idx_invitations_email ON invitations(email);
CREATE INDEX IF NOT EXISTS idx_invitations_token ON invitations(token);
CREATE INDEX IF NOT EXISTS idx_lorries_warehouse ON lorries(warehouse);
CREATE INDEX IF NOT EXISTS idx_maint_lorry ON lorry_maintenance(lorry_id);
CREATE INDEX IF NOT EXISTS idx_maint_unavail ON lorry_maintenance(unavailable_from, unavailable_to);
CREATE INDEX IF NOT EXISTS idx_od_proposed_date ON order_details(proposed_delivery_date);
CREATE INDEX IF NOT EXISTS idx_od_state ON order_details(state);
CREATE INDEX IF NOT EXISTS idx_od_warehouse ON order_details(warehouse);
CREATE INDEX IF NOT EXISTS idx_organizers_active ON project_organizers(active);
CREATE INDEX IF NOT EXISTS idx_overdue_date ON overdue_history(pull_date);
CREATE INDEX IF NOT EXISTS idx_pa_project ON project_attachments(project_id, category);
CREATE INDEX IF NOT EXISTS idx_pa_role ON project_attachments(project_id, uploaded_by_role);
CREATE INDEX IF NOT EXISTS idx_pact_project ON project_activity(project_id, created_at);
CREATE INDEX IF NOT EXISTS idx_pc_due ON project_checklist(due_date);
CREATE INDEX IF NOT EXISTS idx_pc_owner ON project_checklist(owner_user_id, status);
CREATE INDEX IF NOT EXISTS idx_pc_project ON project_checklist(project_id, seq);
CREATE INDEX IF NOT EXISTS idx_pcatt_item ON project_checklist_attachments(item_id, archived_at);
CREATE INDEX IF NOT EXISTS idx_pcc_item ON project_checklist_comments(item_id, created_at);
CREATE INDEX IF NOT EXISTS idx_pcs_project ON project_checklist_sections(project_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_pcti_template ON project_checklist_template_items(template_id, seq);
CREATE INDEX IF NOT EXISTS idx_pcts_template ON project_checklist_template_sections(template_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_pd_project ON project_defects(project_id, phase);
CREATE INDEX IF NOT EXISTS idx_petty_cash_archived ON petty_cash_entries(archived_at);
CREATE INDEX IF NOT EXISTS idx_petty_cash_category ON petty_cash_entries(category);
CREATE INDEX IF NOT EXISTS idx_petty_cash_occurred ON petty_cash_entries(occurred_on DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_pfl_auto_source ON project_finance_lines(project_id, auto_source);
CREATE INDEX IF NOT EXISTS idx_pfl_category ON project_finance_lines(category);
CREATE INDEX IF NOT EXISTS idx_pfl_project ON project_finance_lines(project_id, kind, category);
CREATE INDEX IF NOT EXISTS idx_po_amount ON purchase_orders(doc_date, amount);
CREATE INDEX IF NOT EXISTS idx_po_doc ON purchase_orders(doc_no);
CREATE INDEX IF NOT EXISTS idx_po_docs_creditor ON purchase_order_docs(creditor_code);
CREATE INDEX IF NOT EXISTS idx_po_docs_date ON purchase_order_docs(doc_date);
CREATE INDEX IF NOT EXISTS idx_po_docs_status ON purchase_order_docs(cancelled, doc_status);
CREATE INDEX IF NOT EXISTS idx_point_tx_reason       ON point_transactions(reason, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_point_tx_user_created ON point_transactions(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pr_token ON password_resets(token);
CREATE INDEX IF NOT EXISTS idx_pr_user ON password_resets(user_id, consumed_at);
CREATE INDEX IF NOT EXISTS idx_project_activity_project_created ON project_activity(project_id, created_at);
CREATE INDEX IF NOT EXISTS idx_project_checklist_project_due ON project_checklist(project_id, due_date);
CREATE INDEX IF NOT EXISTS idx_project_phase_photos_proj_phase ON project_phase_photos(project_id, phase, uploaded_at DESC);
CREATE INDEX IF NOT EXISTS idx_project_reads_user ON project_reads(user_id, last_read_at DESC);
CREATE INDEX IF NOT EXISTS idx_project_sales_attendees_rep ON project_sales_attendees(sales_rep_id);
CREATE INDEX IF NOT EXISTS idx_projects_archived ON projects(archived_at);
CREATE INDEX IF NOT EXISTS idx_projects_brand    ON projects(brand);
CREATE INDEX IF NOT EXISTS idx_projects_payment  ON projects(payment_status);
CREATE INDEX IF NOT EXISTS idx_projects_pic      ON projects(pic_id);
CREATE INDEX IF NOT EXISTS idx_projects_stage    ON projects(stage);
CREATE INDEX IF NOT EXISTS idx_projects_start    ON projects(start_date);
CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status);
CREATE INDEX IF NOT EXISTS idx_proposal_trips_proposal ON trip_proposal_trips(proposal_id);
CREATE INDEX IF NOT EXISTS idx_psr_project ON project_sales_reports(project_id);
CREATE INDEX IF NOT EXISTS idx_pst_project ON project_stock_transfers(project_id, direction);
CREATE INDEX IF NOT EXISTS idx_ptm_project ON project_team(project_id);
CREATE INDEX IF NOT EXISTS idx_ptm_user ON project_team(user_id);
CREATE INDEX IF NOT EXISTS idx_redemptions_award         ON award_redemptions(award_id);
CREATE INDEX IF NOT EXISTS idx_redemptions_status        ON award_redemptions(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_redemptions_user_created  ON award_redemptions(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_rep_tiers_rep ON sales_rep_commission_tiers(rep_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_role_page_access_role ON role_page_access(role_id);
CREATE INDEX IF NOT EXISTS idx_salary_line_trip ON salary_trip_lines(trip_id);
CREATE INDEX IF NOT EXISTS idx_salary_line_user ON salary_trip_lines(user_id);
CREATE INDEX IF NOT EXISTS idx_salary_period ON salary_records(period);
CREATE INDEX IF NOT EXISTS idx_salary_user ON salary_records(user_id);
CREATE INDEX IF NOT EXISTS idx_sales_entries_by_project ON sales_entries(project_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_sales_entries_by_user ON sales_entries(created_by, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_sales_entries_customer_phone ON sales_entries(customer_phone);
CREATE INDEX IF NOT EXISTS idx_sales_entries_occurred ON sales_entries(occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_sales_entries_ref_no ON sales_entries(ref_no);
CREATE INDEX IF NOT EXISTS idx_sales_entries_rep ON sales_entries(sales_rep_id);
CREATE INDEX IF NOT EXISTS idx_sales_entries_sales_person ON sales_entries(sales_person_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_sales_entries_status ON sales_entries(status);
CREATE INDEX IF NOT EXISTS idx_sales_entry_activity_entry ON sales_entry_activity(entry_id, created_at);
CREATE INDEX IF NOT EXISTS idx_sales_entry_items_entry ON sales_entry_items(entry_id);
CREATE INDEX IF NOT EXISTS idx_sales_entry_payments_entry ON sales_entry_payments(entry_id);
CREATE INDEX IF NOT EXISTS idx_sales_positions_active ON sales_positions(active);
CREATE INDEX IF NOT EXISTS idx_sales_rep_brands_brand ON sales_rep_brands(brand);
CREATE INDEX IF NOT EXISTS idx_sales_reps_archived ON sales_reps(archived_at);
CREATE INDEX IF NOT EXISTS idx_sales_reps_position ON sales_reps(position_id);
CREATE INDEX IF NOT EXISTS idx_sales_reps_status   ON sales_reps(status);
CREATE INDEX IF NOT EXISTS idx_sales_reps_upline   ON sales_reps(upline_id);
CREATE INDEX IF NOT EXISTS idx_sales_reps_user     ON sales_reps(user_id);
CREATE INDEX IF NOT EXISTS idx_sales_team_activity_rep ON sales_team_activity(rep_id, created_at);
CREATE INDEX IF NOT EXISTS idx_sales_tiers_active ON sales_commission_tiers(active);
CREATE INDEX IF NOT EXISTS idx_sc_assr ON supplier_communications(assr_id);
CREATE INDEX IF NOT EXISTS idx_sc_supplier ON supplier_communications(supplier_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_so_balance ON sales_orders(balance);
CREATE INDEX IF NOT EXISTS idx_so_region ON sales_orders(region);
CREATE INDEX IF NOT EXISTS idx_so_sync ON sales_orders(sync_status);
CREATE INDEX IF NOT EXISTS idx_stock_items_item_group   ON stock_items(item_group);
CREATE INDEX IF NOT EXISTS idx_stock_items_main_supplier ON stock_items(main_supplier);
CREATE INDEX IF NOT EXISTS idx_suggestions_archived ON suggestions(archived_at);
CREATE INDEX IF NOT EXISTS idx_suggestions_status_created ON suggestions(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_suggestions_user_created   ON suggestions(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supplier_accounts_status   ON supplier_accounts(status);
CREATE INDEX IF NOT EXISTS idx_supplier_accounts_supplier ON supplier_accounts(supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_invitations_account ON supplier_invitations(supplier_account_id);
CREATE INDEX IF NOT EXISTS idx_supplier_sessions_exp ON supplier_sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_suppliers_active ON suppliers(active);
CREATE INDEX IF NOT EXISTS idx_suppliers_name ON suppliers(name);
CREATE INDEX IF NOT EXISTS idx_survey_assr ON assr_survey_tokens(assr_id);
CREATE INDEX IF NOT EXISTS idx_trip_locations_trip ON trip_locations(trip_id, recorded_at);
CREATE INDEX IF NOT EXISTS idx_trip_stops_doc ON trip_stops(doc_no);
CREATE INDEX IF NOT EXISTS idx_trip_stops_trip ON trip_stops(trip_id);
CREATE INDEX IF NOT EXISTS idx_trips_date ON trips(trip_date);
CREATE INDEX IF NOT EXISTS idx_trips_driver ON trips(driver_user_id);
CREATE INDEX IF NOT EXISTS idx_trips_project ON trips(project_id);
CREATE INDEX IF NOT EXISTS idx_trips_status ON trips(status);
CREATE INDEX IF NOT EXISTS idx_trips_warehouse ON trips(warehouse);
CREATE INDEX IF NOT EXISTS idx_udf_fields_table ON udf_fields(table_name);
CREATE INDEX IF NOT EXISTS idx_udf_values_table ON udf_values(table_name);
CREATE INDEX IF NOT EXISTS idx_user_brands_brand ON user_brands(brand);
CREATE INDEX IF NOT EXISTS idx_users_department ON users(department_id);
CREATE INDEX IF NOT EXISTS idx_users_last_seen ON users(last_seen_at);
CREATE INDEX IF NOT EXISTS idx_users_manager ON users(manager_id);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role_id);
CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);
CREATE INDEX IF NOT EXISTS idx_users_type ON users(user_type);
CREATE INDEX IF NOT EXISTS idx_venues_active ON project_venues(active);
CREATE INDEX IF NOT EXISTS idx_votes_target ON votes(target_type, target_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_sales_entries_doc_no ON sales_entries(doc_no) WHERE doc_no IS NOT NULL;
