-- Sales-entry change-request queue (Part B — edit-approval workflow). A rep
-- editing an already-submitted (non-draft) sales entry does NOT mutate it
-- directly; the proposed PATCH body is parked here as a 'pending' request for a
-- Sales Director to approve (which re-applies it to the entry) or reject. One
-- live pending request per entry — a newer edit supersedes the older one.
-- Additive + idempotent; public schema (sales_entries lives in public).
--
-- payload is stored as TEXT (a JSON string) rather than jsonb so the D1-compat
-- write path and the test-D1 mirror (migrations/103) stay byte-identical — the
-- app only ever round-trips it through JSON.parse, never queries inside it.

CREATE TABLE IF NOT EXISTS sales_entry_change_requests (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_id      bigint NOT NULL REFERENCES sales_entries(id) ON DELETE CASCADE,
  payload       text NOT NULL,
  summary       text,
  status        text NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','approved','rejected','superseded')),
  requested_by  bigint,
  decided_by    bigint,
  decided_at    text,
  decide_note   text,
  created_at    text NOT NULL DEFAULT (now()::text)
);

CREATE INDEX IF NOT EXISTS idx_secr_entry_status ON sales_entry_change_requests (entry_id, status);
CREATE INDEX IF NOT EXISTS idx_secr_status ON sales_entry_change_requests (status);
