-- 0093: multi-company company_id stamp for the NATIVE (public-schema) modules
-- that 0083 skipped — Projects, Announcements, Calendar events.
--
-- P0 cross-company leak (2026-07-13 audit): the companyContext middleware is
-- live and the SCM + sales/finance surfaces are scoped, but the native raw-SQL
-- modules (projects.ts / announcements.ts / events.ts / search.ts and the
-- notification/inbox feeds derived from them) had NO company_id column at all,
-- so a 2990 user saw every Houzs project, announcement, calendar event and
-- search hit. This migration adds the column; the paired code change adds the
-- per-request predicates.
--
-- Pattern EXACTLY mirrors 0089/0092 (one single-line DO block per table so the
-- pg-migrate runner's ';\n' splitter keeps each block whole):
--   relkind ('r','p') guard  ->  resolve HOUZS id into a DECLAREd variable
--   (a DEFAULT expression cannot be a subquery, see 0092)  ->  ADD COLUMN IF
--   NOT EXISTS  ->  backfill existing rows to HOUZS (all existing data is
--   Houzs's today)  ->  SET NOT NULL  ->  SET DEFAULT <houzs id> via EXECUTE
--   format  ->  FK public.companies  ->  index.
--
-- Tables stamped (14):
--   projects + child tables: project_checklist, project_checklist_sections,
--     project_checklist_attachments, project_checklist_comments,
--     project_checklist_templates, project_checklist_template_sections,
--     project_checklist_template_items, project_venues, project_brands,
--     project_activity
--   announcements, announcement_acks
--   events (manual calendar entries)
--
-- NOTES:
--   * The DEFAULT is the same safety-net 0091 gave every other company_id
--     column — an unstamped insert lands on the base company instead of
--     violating NOT NULL.
--   * project_checklist* child rows + project_activity are read exclusively
--     through their parent project (project_id joins), which the code change
--     scopes — their own company_id is a schema-parity backstop.
--   * Deliberately NOT converting single-company UNIQUEs (projects.code,
--     project_brands.name) to UNIQUE(company_id, ...): the projects module is
--     Houzs-only today; revisit if 2990 starts using PMS.
--
-- ADDITIVE + idempotent + re-run-safe.

-- public.projects
DO $$ DECLARE hid bigint; BEGIN IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='projects' AND c.relkind IN ('r','p')) THEN SELECT id INTO hid FROM public.companies WHERE code = 'HOUZS'; IF hid IS NULL THEN RETURN; END IF; ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS company_id bigint; EXECUTE format('UPDATE public.projects SET company_id = %s WHERE company_id IS NULL', hid); ALTER TABLE public.projects ALTER COLUMN company_id SET NOT NULL; EXECUTE format('ALTER TABLE public.projects ALTER COLUMN company_id SET DEFAULT %s', hid); ALTER TABLE public.projects DROP CONSTRAINT IF EXISTS projects_company_id_fkey; ALTER TABLE public.projects ADD CONSTRAINT projects_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id); CREATE INDEX IF NOT EXISTS idx_projects_company_id ON public.projects (company_id); END IF; END $$;

-- public.project_checklist
DO $$ DECLARE hid bigint; BEGIN IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='project_checklist' AND c.relkind IN ('r','p')) THEN SELECT id INTO hid FROM public.companies WHERE code = 'HOUZS'; IF hid IS NULL THEN RETURN; END IF; ALTER TABLE public.project_checklist ADD COLUMN IF NOT EXISTS company_id bigint; EXECUTE format('UPDATE public.project_checklist SET company_id = %s WHERE company_id IS NULL', hid); ALTER TABLE public.project_checklist ALTER COLUMN company_id SET NOT NULL; EXECUTE format('ALTER TABLE public.project_checklist ALTER COLUMN company_id SET DEFAULT %s', hid); ALTER TABLE public.project_checklist DROP CONSTRAINT IF EXISTS project_checklist_company_id_fkey; ALTER TABLE public.project_checklist ADD CONSTRAINT project_checklist_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id); CREATE INDEX IF NOT EXISTS idx_project_checklist_company_id ON public.project_checklist (company_id); END IF; END $$;

-- public.project_checklist_sections
DO $$ DECLARE hid bigint; BEGIN IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='project_checklist_sections' AND c.relkind IN ('r','p')) THEN SELECT id INTO hid FROM public.companies WHERE code = 'HOUZS'; IF hid IS NULL THEN RETURN; END IF; ALTER TABLE public.project_checklist_sections ADD COLUMN IF NOT EXISTS company_id bigint; EXECUTE format('UPDATE public.project_checklist_sections SET company_id = %s WHERE company_id IS NULL', hid); ALTER TABLE public.project_checklist_sections ALTER COLUMN company_id SET NOT NULL; EXECUTE format('ALTER TABLE public.project_checklist_sections ALTER COLUMN company_id SET DEFAULT %s', hid); ALTER TABLE public.project_checklist_sections DROP CONSTRAINT IF EXISTS project_checklist_sections_company_id_fkey; ALTER TABLE public.project_checklist_sections ADD CONSTRAINT project_checklist_sections_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id); CREATE INDEX IF NOT EXISTS idx_project_checklist_sections_company_id ON public.project_checklist_sections (company_id); END IF; END $$;

-- public.project_checklist_attachments
DO $$ DECLARE hid bigint; BEGIN IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='project_checklist_attachments' AND c.relkind IN ('r','p')) THEN SELECT id INTO hid FROM public.companies WHERE code = 'HOUZS'; IF hid IS NULL THEN RETURN; END IF; ALTER TABLE public.project_checklist_attachments ADD COLUMN IF NOT EXISTS company_id bigint; EXECUTE format('UPDATE public.project_checklist_attachments SET company_id = %s WHERE company_id IS NULL', hid); ALTER TABLE public.project_checklist_attachments ALTER COLUMN company_id SET NOT NULL; EXECUTE format('ALTER TABLE public.project_checklist_attachments ALTER COLUMN company_id SET DEFAULT %s', hid); ALTER TABLE public.project_checklist_attachments DROP CONSTRAINT IF EXISTS project_checklist_attachments_company_id_fkey; ALTER TABLE public.project_checklist_attachments ADD CONSTRAINT project_checklist_attachments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id); CREATE INDEX IF NOT EXISTS idx_project_checklist_attachments_company_id ON public.project_checklist_attachments (company_id); END IF; END $$;

-- public.project_checklist_comments
DO $$ DECLARE hid bigint; BEGIN IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='project_checklist_comments' AND c.relkind IN ('r','p')) THEN SELECT id INTO hid FROM public.companies WHERE code = 'HOUZS'; IF hid IS NULL THEN RETURN; END IF; ALTER TABLE public.project_checklist_comments ADD COLUMN IF NOT EXISTS company_id bigint; EXECUTE format('UPDATE public.project_checklist_comments SET company_id = %s WHERE company_id IS NULL', hid); ALTER TABLE public.project_checklist_comments ALTER COLUMN company_id SET NOT NULL; EXECUTE format('ALTER TABLE public.project_checklist_comments ALTER COLUMN company_id SET DEFAULT %s', hid); ALTER TABLE public.project_checklist_comments DROP CONSTRAINT IF EXISTS project_checklist_comments_company_id_fkey; ALTER TABLE public.project_checklist_comments ADD CONSTRAINT project_checklist_comments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id); CREATE INDEX IF NOT EXISTS idx_project_checklist_comments_company_id ON public.project_checklist_comments (company_id); END IF; END $$;

-- public.project_checklist_templates
DO $$ DECLARE hid bigint; BEGIN IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='project_checklist_templates' AND c.relkind IN ('r','p')) THEN SELECT id INTO hid FROM public.companies WHERE code = 'HOUZS'; IF hid IS NULL THEN RETURN; END IF; ALTER TABLE public.project_checklist_templates ADD COLUMN IF NOT EXISTS company_id bigint; EXECUTE format('UPDATE public.project_checklist_templates SET company_id = %s WHERE company_id IS NULL', hid); ALTER TABLE public.project_checklist_templates ALTER COLUMN company_id SET NOT NULL; EXECUTE format('ALTER TABLE public.project_checklist_templates ALTER COLUMN company_id SET DEFAULT %s', hid); ALTER TABLE public.project_checklist_templates DROP CONSTRAINT IF EXISTS project_checklist_templates_company_id_fkey; ALTER TABLE public.project_checklist_templates ADD CONSTRAINT project_checklist_templates_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id); CREATE INDEX IF NOT EXISTS idx_project_checklist_templates_company_id ON public.project_checklist_templates (company_id); END IF; END $$;

-- public.project_checklist_template_sections
DO $$ DECLARE hid bigint; BEGIN IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='project_checklist_template_sections' AND c.relkind IN ('r','p')) THEN SELECT id INTO hid FROM public.companies WHERE code = 'HOUZS'; IF hid IS NULL THEN RETURN; END IF; ALTER TABLE public.project_checklist_template_sections ADD COLUMN IF NOT EXISTS company_id bigint; EXECUTE format('UPDATE public.project_checklist_template_sections SET company_id = %s WHERE company_id IS NULL', hid); ALTER TABLE public.project_checklist_template_sections ALTER COLUMN company_id SET NOT NULL; EXECUTE format('ALTER TABLE public.project_checklist_template_sections ALTER COLUMN company_id SET DEFAULT %s', hid); ALTER TABLE public.project_checklist_template_sections DROP CONSTRAINT IF EXISTS project_checklist_template_sections_company_id_fkey; ALTER TABLE public.project_checklist_template_sections ADD CONSTRAINT project_checklist_template_sections_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id); CREATE INDEX IF NOT EXISTS idx_project_checklist_template_sections_company_id ON public.project_checklist_template_sections (company_id); END IF; END $$;

-- public.project_checklist_template_items
DO $$ DECLARE hid bigint; BEGIN IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='project_checklist_template_items' AND c.relkind IN ('r','p')) THEN SELECT id INTO hid FROM public.companies WHERE code = 'HOUZS'; IF hid IS NULL THEN RETURN; END IF; ALTER TABLE public.project_checklist_template_items ADD COLUMN IF NOT EXISTS company_id bigint; EXECUTE format('UPDATE public.project_checklist_template_items SET company_id = %s WHERE company_id IS NULL', hid); ALTER TABLE public.project_checklist_template_items ALTER COLUMN company_id SET NOT NULL; EXECUTE format('ALTER TABLE public.project_checklist_template_items ALTER COLUMN company_id SET DEFAULT %s', hid); ALTER TABLE public.project_checklist_template_items DROP CONSTRAINT IF EXISTS project_checklist_template_items_company_id_fkey; ALTER TABLE public.project_checklist_template_items ADD CONSTRAINT project_checklist_template_items_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id); CREATE INDEX IF NOT EXISTS idx_project_checklist_template_items_company_id ON public.project_checklist_template_items (company_id); END IF; END $$;

-- public.project_venues
DO $$ DECLARE hid bigint; BEGIN IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='project_venues' AND c.relkind IN ('r','p')) THEN SELECT id INTO hid FROM public.companies WHERE code = 'HOUZS'; IF hid IS NULL THEN RETURN; END IF; ALTER TABLE public.project_venues ADD COLUMN IF NOT EXISTS company_id bigint; EXECUTE format('UPDATE public.project_venues SET company_id = %s WHERE company_id IS NULL', hid); ALTER TABLE public.project_venues ALTER COLUMN company_id SET NOT NULL; EXECUTE format('ALTER TABLE public.project_venues ALTER COLUMN company_id SET DEFAULT %s', hid); ALTER TABLE public.project_venues DROP CONSTRAINT IF EXISTS project_venues_company_id_fkey; ALTER TABLE public.project_venues ADD CONSTRAINT project_venues_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id); CREATE INDEX IF NOT EXISTS idx_project_venues_company_id ON public.project_venues (company_id); END IF; END $$;

-- public.project_brands
DO $$ DECLARE hid bigint; BEGIN IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='project_brands' AND c.relkind IN ('r','p')) THEN SELECT id INTO hid FROM public.companies WHERE code = 'HOUZS'; IF hid IS NULL THEN RETURN; END IF; ALTER TABLE public.project_brands ADD COLUMN IF NOT EXISTS company_id bigint; EXECUTE format('UPDATE public.project_brands SET company_id = %s WHERE company_id IS NULL', hid); ALTER TABLE public.project_brands ALTER COLUMN company_id SET NOT NULL; EXECUTE format('ALTER TABLE public.project_brands ALTER COLUMN company_id SET DEFAULT %s', hid); ALTER TABLE public.project_brands DROP CONSTRAINT IF EXISTS project_brands_company_id_fkey; ALTER TABLE public.project_brands ADD CONSTRAINT project_brands_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id); CREATE INDEX IF NOT EXISTS idx_project_brands_company_id ON public.project_brands (company_id); END IF; END $$;

-- public.project_activity
DO $$ DECLARE hid bigint; BEGIN IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='project_activity' AND c.relkind IN ('r','p')) THEN SELECT id INTO hid FROM public.companies WHERE code = 'HOUZS'; IF hid IS NULL THEN RETURN; END IF; ALTER TABLE public.project_activity ADD COLUMN IF NOT EXISTS company_id bigint; EXECUTE format('UPDATE public.project_activity SET company_id = %s WHERE company_id IS NULL', hid); ALTER TABLE public.project_activity ALTER COLUMN company_id SET NOT NULL; EXECUTE format('ALTER TABLE public.project_activity ALTER COLUMN company_id SET DEFAULT %s', hid); ALTER TABLE public.project_activity DROP CONSTRAINT IF EXISTS project_activity_company_id_fkey; ALTER TABLE public.project_activity ADD CONSTRAINT project_activity_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id); CREATE INDEX IF NOT EXISTS idx_project_activity_company_id ON public.project_activity (company_id); END IF; END $$;

-- public.announcements
DO $$ DECLARE hid bigint; BEGIN IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='announcements' AND c.relkind IN ('r','p')) THEN SELECT id INTO hid FROM public.companies WHERE code = 'HOUZS'; IF hid IS NULL THEN RETURN; END IF; ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS company_id bigint; EXECUTE format('UPDATE public.announcements SET company_id = %s WHERE company_id IS NULL', hid); ALTER TABLE public.announcements ALTER COLUMN company_id SET NOT NULL; EXECUTE format('ALTER TABLE public.announcements ALTER COLUMN company_id SET DEFAULT %s', hid); ALTER TABLE public.announcements DROP CONSTRAINT IF EXISTS announcements_company_id_fkey; ALTER TABLE public.announcements ADD CONSTRAINT announcements_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id); CREATE INDEX IF NOT EXISTS idx_announcements_company_id ON public.announcements (company_id); END IF; END $$;

-- public.announcement_acks
DO $$ DECLARE hid bigint; BEGIN IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='announcement_acks' AND c.relkind IN ('r','p')) THEN SELECT id INTO hid FROM public.companies WHERE code = 'HOUZS'; IF hid IS NULL THEN RETURN; END IF; ALTER TABLE public.announcement_acks ADD COLUMN IF NOT EXISTS company_id bigint; EXECUTE format('UPDATE public.announcement_acks SET company_id = %s WHERE company_id IS NULL', hid); ALTER TABLE public.announcement_acks ALTER COLUMN company_id SET NOT NULL; EXECUTE format('ALTER TABLE public.announcement_acks ALTER COLUMN company_id SET DEFAULT %s', hid); ALTER TABLE public.announcement_acks DROP CONSTRAINT IF EXISTS announcement_acks_company_id_fkey; ALTER TABLE public.announcement_acks ADD CONSTRAINT announcement_acks_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id); CREATE INDEX IF NOT EXISTS idx_announcement_acks_company_id ON public.announcement_acks (company_id); END IF; END $$;

-- public.events
DO $$ DECLARE hid bigint; BEGIN IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='events' AND c.relkind IN ('r','p')) THEN SELECT id INTO hid FROM public.companies WHERE code = 'HOUZS'; IF hid IS NULL THEN RETURN; END IF; ALTER TABLE public.events ADD COLUMN IF NOT EXISTS company_id bigint; EXECUTE format('UPDATE public.events SET company_id = %s WHERE company_id IS NULL', hid); ALTER TABLE public.events ALTER COLUMN company_id SET NOT NULL; EXECUTE format('ALTER TABLE public.events ALTER COLUMN company_id SET DEFAULT %s', hid); ALTER TABLE public.events DROP CONSTRAINT IF EXISTS events_company_id_fkey; ALTER TABLE public.events ADD CONSTRAINT events_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id); CREATE INDEX IF NOT EXISTS idx_events_company_id ON public.events (company_id); END IF; END $$;
