-- 0114: make the last 5 SHARED config tables PER-COMPANY (owner 2026-07-15 "分").
--
-- Rule: only Service + Delivery(TMS) are shared; everything else is per-company.
-- These 5 config tables were still shared:
--   1) delivery_fee_config       — singleton (id=1); company_id added by 0083.
--   2) fabric_tier_addon_config   — singleton (id=1); company_id added by 0083.
--   3) sofa_combo_anchor          — multi-row (PK base_model); NO company_id yet.
--   4) mrp_category_lead_times    — multi-row uniq(warehouse_id,category); NULL
--                                   warehouse bucket was shared; NO company_id.
--   5) so_settings                — keyed by `key`; NO company_id (0092 parked it).
--
-- Each block is self-contained + idempotent: adds company_id (0083 pattern,
-- backfill existing → HOUZS), rekeys the PK/unique to include company_id, and
-- seeds a company-2 row where the table must not be empty for 2990 to work
-- (fee/fabric-tier = copy HOUZS values as a starting point; mrp = zero-default
-- global bucket; so_settings = copy toggle set). sofa_combo_anchor needs no seed
-- (anchors are optional per base_model). One-line DO blocks (runner splits on
-- ';\n'); guarded by pg_class relkind so an absent table is skipped, and by a
-- non-null HOUZS id so a pre-companies deploy no-ops. STAGING-FIRST.

-- 1) delivery_fee_config — singleton: rekey PK id -> (company_id,id) + seed 2990 copy
DO $$ DECLARE hid bigint; tid bigint; BEGIN IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='scm' AND c.relname='delivery_fee_config' AND c.relkind IN ('r','p')) THEN SELECT id INTO hid FROM public.companies WHERE code='HOUZS'; SELECT id INTO tid FROM public.companies WHERE code='2990'; IF hid IS NULL THEN RETURN; END IF; ALTER TABLE scm.delivery_fee_config ADD COLUMN IF NOT EXISTS company_id bigint; EXECUTE format('UPDATE scm.delivery_fee_config SET company_id=%s WHERE company_id IS NULL', hid); ALTER TABLE scm.delivery_fee_config ALTER COLUMN company_id SET NOT NULL; ALTER TABLE scm.delivery_fee_config DROP CONSTRAINT IF EXISTS delivery_fee_config_company_id_fkey; ALTER TABLE scm.delivery_fee_config ADD CONSTRAINT delivery_fee_config_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id); ALTER TABLE scm.delivery_fee_config DROP CONSTRAINT IF EXISTS delivery_fee_config_pkey; ALTER TABLE scm.delivery_fee_config ADD PRIMARY KEY (company_id, id); IF tid IS NOT NULL THEN INSERT INTO scm.delivery_fee_config (id, company_id, base_fee, cross_category_fee, mattress_bedframe_lead_days, sofa_lead_days) SELECT 1, tid, base_fee, cross_category_fee, mattress_bedframe_lead_days, sofa_lead_days FROM scm.delivery_fee_config WHERE company_id=hid ON CONFLICT DO NOTHING; END IF; END IF; END $$;

-- 2) fabric_tier_addon_config — singleton: rekey PK id -> (company_id,id) + seed 2990 copy
DO $$ DECLARE hid bigint; tid bigint; BEGIN IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='scm' AND c.relname='fabric_tier_addon_config' AND c.relkind IN ('r','p')) THEN SELECT id INTO hid FROM public.companies WHERE code='HOUZS'; SELECT id INTO tid FROM public.companies WHERE code='2990'; IF hid IS NULL THEN RETURN; END IF; ALTER TABLE scm.fabric_tier_addon_config ADD COLUMN IF NOT EXISTS company_id bigint; EXECUTE format('UPDATE scm.fabric_tier_addon_config SET company_id=%s WHERE company_id IS NULL', hid); ALTER TABLE scm.fabric_tier_addon_config ALTER COLUMN company_id SET NOT NULL; ALTER TABLE scm.fabric_tier_addon_config DROP CONSTRAINT IF EXISTS fabric_tier_addon_config_company_id_fkey; ALTER TABLE scm.fabric_tier_addon_config ADD CONSTRAINT fabric_tier_addon_config_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id); ALTER TABLE scm.fabric_tier_addon_config DROP CONSTRAINT IF EXISTS fabric_tier_addon_config_pkey; ALTER TABLE scm.fabric_tier_addon_config ADD PRIMARY KEY (company_id, id); IF tid IS NOT NULL THEN INSERT INTO scm.fabric_tier_addon_config (id, company_id, sofa_tier2_delta, sofa_tier3_delta, bedframe_tier2_delta, bedframe_tier3_delta) SELECT 1, tid, sofa_tier2_delta, sofa_tier3_delta, bedframe_tier2_delta, bedframe_tier3_delta FROM scm.fabric_tier_addon_config WHERE company_id=hid ON CONFLICT DO NOTHING; END IF; END IF; END $$;

-- 3) sofa_combo_anchor — multi-row: add company_id + rekey PK base_model -> (company_id,base_model). No seed (anchors optional).
DO $$ DECLARE hid bigint; BEGIN IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='scm' AND c.relname='sofa_combo_anchor' AND c.relkind IN ('r','p')) THEN SELECT id INTO hid FROM public.companies WHERE code='HOUZS'; IF hid IS NULL THEN RETURN; END IF; ALTER TABLE scm.sofa_combo_anchor ADD COLUMN IF NOT EXISTS company_id bigint; EXECUTE format('UPDATE scm.sofa_combo_anchor SET company_id=%s WHERE company_id IS NULL', hid); ALTER TABLE scm.sofa_combo_anchor ALTER COLUMN company_id SET NOT NULL; ALTER TABLE scm.sofa_combo_anchor DROP CONSTRAINT IF EXISTS sofa_combo_anchor_company_id_fkey; ALTER TABLE scm.sofa_combo_anchor ADD CONSTRAINT sofa_combo_anchor_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id); CREATE INDEX IF NOT EXISTS idx_sofa_combo_anchor_company_id ON scm.sofa_combo_anchor (company_id); ALTER TABLE scm.sofa_combo_anchor DROP CONSTRAINT IF EXISTS sofa_combo_anchor_pkey; ALTER TABLE scm.sofa_combo_anchor ADD PRIMARY KEY (company_id, base_model); END IF; END $$;

-- 4) mrp_category_lead_times — multi-row: add company_id + rekey uniq(warehouse_id,category) -> (company_id,warehouse_id,category) NULLS NOT DISTINCT + seed 2990 global bucket (5 cats @ 0)
DO $$ DECLARE hid bigint; tid bigint; BEGIN IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='scm' AND c.relname='mrp_category_lead_times' AND c.relkind IN ('r','p')) THEN SELECT id INTO hid FROM public.companies WHERE code='HOUZS'; SELECT id INTO tid FROM public.companies WHERE code='2990'; IF hid IS NULL THEN RETURN; END IF; ALTER TABLE scm.mrp_category_lead_times ADD COLUMN IF NOT EXISTS company_id bigint; EXECUTE format('UPDATE scm.mrp_category_lead_times SET company_id=%s WHERE company_id IS NULL', hid); ALTER TABLE scm.mrp_category_lead_times ALTER COLUMN company_id SET NOT NULL; ALTER TABLE scm.mrp_category_lead_times DROP CONSTRAINT IF EXISTS mrp_category_lead_times_company_id_fkey; ALTER TABLE scm.mrp_category_lead_times ADD CONSTRAINT mrp_category_lead_times_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id); DROP INDEX IF EXISTS scm.mrp_category_lead_times_wh_cat_uniq; CREATE UNIQUE INDEX IF NOT EXISTS mrp_category_lead_times_co_wh_cat_uniq ON scm.mrp_category_lead_times (company_id, warehouse_id, category) NULLS NOT DISTINCT; IF tid IS NOT NULL THEN INSERT INTO scm.mrp_category_lead_times (company_id, warehouse_id, category, lead_days) SELECT tid, NULL::uuid, unnest(ARRAY['sofa','bedframe','mattress','accessory','service']), 0 ON CONFLICT DO NOTHING; END IF; END IF; END $$;

-- 5) so_settings — keyed by `key`: add company_id + rekey PK key -> (company_id,key) + seed 2990 copy of toggle set
DO $$ DECLARE hid bigint; tid bigint; BEGIN IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='scm' AND c.relname='so_settings' AND c.relkind IN ('r','p')) THEN SELECT id INTO hid FROM public.companies WHERE code='HOUZS'; SELECT id INTO tid FROM public.companies WHERE code='2990'; IF hid IS NULL THEN RETURN; END IF; ALTER TABLE scm.so_settings ADD COLUMN IF NOT EXISTS company_id bigint; EXECUTE format('UPDATE scm.so_settings SET company_id=%s WHERE company_id IS NULL', hid); ALTER TABLE scm.so_settings ALTER COLUMN company_id SET NOT NULL; ALTER TABLE scm.so_settings DROP CONSTRAINT IF EXISTS so_settings_company_id_fkey; ALTER TABLE scm.so_settings ADD CONSTRAINT so_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id); ALTER TABLE scm.so_settings DROP CONSTRAINT IF EXISTS so_settings_pkey; ALTER TABLE scm.so_settings ADD PRIMARY KEY (company_id, key); IF tid IS NOT NULL THEN INSERT INTO scm.so_settings (company_id, key, enabled, label) SELECT tid, key, enabled, label FROM scm.so_settings WHERE company_id=hid ON CONFLICT DO NOTHING; END IF; END IF; END $$;
